### ISSUE TITLE
Figure out a way to get inputs from an external file/action

### ISSUE THREAD

**Issue by kvmware** [knative/actions#56]
Adding on from https://github.com/knative/actions/issues/55 the settings for the enable logic should be sourced from an external source so that we can sync the toplevel across repos destructively without worrying about individual repo settings which should not be touched by a file syncer.

**Comment by kvmware** [comment]
This should do it
```
jobs:
  read_config:
    runs-on: ubuntu-latest
    outputs:
      use-style: ${{ steps.config.outputs.use-style }}
      use-blah: ${{ steps.config.outputs.use-blah }}
    steps:
    - uses: actions/checkout@v3
    - id: config
      run: |
        echo "::set-output name=use-style::$(yq '.use-style' config.yaml 2>>/dev/null|| echo true)"
        echo "::set-output name=use-blah::$(yq '.use-blah' config.yaml 2>>/dev/null|| echo true)"

  style:
      needs: read_config
      if: ${{needs.read_config.outputs.use-blah == 'true'}}
      uses: knative/actions/.github/workflows/style.yaml@main
```
